"""empty message

Revision ID: 763be2c1d905
Revises: 
Create Date: 2023-12-21 13:57:15.250125

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "763be2c1d905"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
